name: elector
services:
  electoric:
    build:
      context: .
    environment:
      - TZ=America/New_York # Remember to change!
    volumes:
      - ./data:/app/data # After the config is generated, you may make this read only
    restart: unless-stopped